import mongoose from "mongoose";

const resourceSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: true,
      trim: true,
    },
    url: {
      type: String,
      required: true,
    },
    type: {
      type: String,
      enum: ["pdf", "link", "slides", "code", "other"],
      default: "link",
    },
  },
  { _id: false }
);

const lessonSchema = new mongoose.Schema(
  {
    title: {
      type: String,
      required: true,
      trim: true,
    },
    module: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Module",
      required: true,
    },
    course: {
      type: mongoose.Schema.Types.ObjectId,
      ref: "Course",
      required: true,
    },
    videoUrl: {
      type: String,
      required: true, // cloudinary url or youtube embed url
    },
    duration: {
      type: Number,
      default: 0, // duration in seconds
    },
    order: {
      type: Number,
      required: true, // position within module
    },
    transcript: {
      type: String, // auto-generated by Whisper AI
      default: "",
    },
    summary: {
      type: String, // AI-generated 5-bullet summary
      default: "",
    },
    resources: [resourceSchema],
    isFree: {
      type: Boolean,
      default: false, // free preview lesson (accessible without enrollment)
    },
    description: {
      type: String,
      trim: true,
    },
  },
  {
    timestamps: true,
  }
);

// ensure order is unique within a module
lessonSchema.index({ module: 1, order: 1 }, { unique: true });

export const Lesson = mongoose.model("Lesson", lessonSchema);